name: CI

on:
  push:
    branches: [dev]
  pull_request:
    branches: [dev]

permissions:
  contents: read

env:
  GITHUB_ACTIONS: true
  NODE_VERSION: 22
  PNPM_VERSION: 9

jobs:
  test:
    name: Run tests
    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:
      - uses: actions/checkout@v4

      - name: Use pnpm ${{ env.PNPM_VERSION }}
        uses: pnpm/action-setup@v4
        with:
          version: ${{ env.PNPM_VERSION }}
          run_install: false

      - name: Use Node.js ${{ env.NODE_VERSION }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: pnpm
          cache-dependency-path: 'package.json'

      - name: Install dependencies
        run: pnpm run clean-install

      - name: Build alpine-typescript
        run: pnpm run build-dist

      - uses: actions/upload-artifact@v4
        with:
          name: test-build-output
          path: |
            ./package.json
            ./dist/*.js
            ./types/*.d.ts

  test-example-package:
    name: Run example package tests
    needs: [test]
    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:
      - uses: actions/checkout@v4
        with:
          sparse-checkout: |
            examples/package
          sparse-checkout-cone-mode: false

      - name: Move example files
        run: |
          mv ./examples/package/* ./
          rm -rf ./examples/package

      - uses: actions/download-artifact@v4
        with:
          name: test-build-output
          path: ./alpine-typescript

      - name: Update alpine-typescript file path
        run: |
          sed -i 's/file:..\/..\//file:alpine-typescript/g' package.json

      - name: Use pnpm ${{ env.PNPM_VERSION }}
        uses: pnpm/action-setup@v4
        with:
          version: ${{ env.PNPM_VERSION }}
          run_install: false

      - name: Use Node.js ${{ env.NODE_VERSION }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: pnpm
          cache-dependency-path: 'package.json'

      - name: Install dependencies
        run: pnpm run clean-install

      - name: Build package example
        run: pnpm run build-dist

  test-example-project:
    name: Run example project tests
    needs: [test]
    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:
      - uses: actions/checkout@v4
        with:
          sparse-checkout: |
            examples/project
          sparse-checkout-cone-mode: false

      - name: Move example files
        run: |
          mv ./examples/project/* ./
          rm -rf ./examples/project

      - uses: actions/download-artifact@v4
        with:
          name: test-build-output
          path: ./alpine-typescript

      - name: Update alpine-typescript file path
        run: |
          sed -i 's/file:..\/..\//file:alpine-typescript/g' package.json

      - name: Use pnpm ${{ env.PNPM_VERSION }}
        uses: pnpm/action-setup@v4
        with:
          version: ${{ env.PNPM_VERSION }}
          run_install: false

      - name: Use Node.js ${{ env.NODE_VERSION }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: pnpm

      - name: Install dependencies
        run: pnpm run clean && pnpm add ./alpine-typescript

      - name: Build package example
        run: pnpm run build-dist

  stage:
    name: Stage changes as pull request
    needs: [test, test-example-package, test-example-project]
    runs-on: ubuntu-latest
    timeout-minutes: 5

    if: github.event_name == 'push'
    steps:
      - run: 'echo "Staging dev changes"'
      - uses: actions/checkout@v4
        with:
          ref: dist

      - name: Reset branch
        run: |
          git fetch origin dev:dev
          git reset --hard dev

      - name: Use pnpm ${{ env.PNPM_VERSION }}
        uses: pnpm/action-setup@v4
        with:
          version: ${{ env.PNPM_VERSION }}
          run_install: false

      - name: Use Node.js ${{ env.NODE_VERSION }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: pnpm
          cache-dependency-path: 'package.json'

      - name: Install dependencies
        run: pnpm run clean-install

      - name: Build alpine-typescript
        run: pnpm run build-dist

      - name: Add dist files
        run: |
          git rm -r --force ./src
          git add --force ./dist/*.js
          git add --force ./types/*.d.ts

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v7
        with:
          token: ${{ secrets.STAGE_DEPLOY_KEY }}
          title: Merge dev changes to dist
          branch: dev-to-dist
          commit-message: '[create-pull-request] update tsc build dist files'
          assignees: JackNoordhuis
