name: Publish Package

on:
  push:
    branches: [dist]
    tags:
      - '*'

permissions:
  contents: read

jobs:
  publish:
    name: Publish to npm registry
    runs-on: ubuntu-latest
    timeout-minutes: 5

    strategy:
      matrix:
        node-version: [18]

    steps:
      - uses: actions/checkout@v4

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      - name: Publish ${{ env.GITHUB_REF_NAME }} to npm registry
        run: |
          npm publish --access public --tag ${{ env.GITHUB_REF_NAME }}
        env:
          NPM_AUTH_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}

      - name: Publish latest to npm registry
        if: ${{ github.ref == 'refs/heads/dist' }}
        run: |
          npm publish --access public --tag latest
        env:
          NPM_AUTH_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}
