name: Publish Package

on:
  push:
    branches: [dist]
    tags:
      - '*'

permissions:
  contents: read

jobs:
  publish:
    name: Publish to npm registry
    runs-on: ubuntu-latest
    timeout-minutes: 5

    strategy:
      matrix:
        node-version: [18]

    steps:
      - uses: actions/checkout@v4

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          registry-url: 'https://registry.npmjs.org'

      - name: Publish ${{ github.ref_name }} to npm registry
        run: |
          npm publish --access public --tag ${{ github.ref_name }}
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}
