name: publish-build

on:
  push:
    branches: [dev]

permissions:
  contents: write

env:
  GITHUB_ACTIONS: true

jobs:
  publish:
    runs-on: ubuntu-latest
    timeout-minutes: 5

    strategy:
      matrix:
        node-version: [18]

    steps:
# TODO: Cache tsc-build output and push to dist branch
